# Generated by Django 4.2.16 on 2026-02-25 12:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(db_index=True, max_length=100, unique=True)),
                ('offered', models.IntegerField(default=0)),
                ('abandoned', models.IntegerField(default=0)),
                ('answered', models.IntegerField(default=0)),
                ('sla_rate', models.FloatField(default=0.0)),
                ('abandon_rate', models.FloatField(default=0.0)),
                ('answer_rate', models.FloatField(default=0.0)),
                ('avg_handle_time', models.FloatField(default=0.0)),
                ('target_ans_rate', models.FloatField(default=0.8)),
                ('target_abd_rate', models.FloatField(default=0.05)),
                ('sla_compliant', models.BooleanField(default=False)),
                ('abd_compliant', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Account Summary',
                'verbose_name_plural': 'Account Summaries',
                'db_table': 'account_summary',
                'ordering': ['sla_rate'],
            },
        ),
        migrations.CreateModel(
            name='DailySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('total_offered', models.IntegerField(default=0)),
                ('total_abandoned', models.IntegerField(default=0)),
                ('total_answered', models.IntegerField(default=0)),
                ('global_sla_rate', models.FloatField(default=0.0)),
                ('global_abandon_rate', models.FloatField(default=0.0)),
                ('global_answer_rate', models.FloatField(default=0.0)),
                ('compliant_accounts', models.IntegerField(default=0)),
                ('total_accounts', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Daily Snapshot',
                'verbose_name_plural': 'Daily Snapshots',
                'db_table': 'daily_snapshots',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SLAConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(db_index=True, max_length=100, unique=True)),
                ('ans_rate_formula', models.CharField(blank=True, max_length=200, null=True)),
                ('abd_rate_formula', models.CharField(blank=True, max_length=200, null=True)),
                ('timeframe_bh', models.IntegerField(default=40, help_text='SLA answer timeframe in seconds (Business Hours)', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(120)])),
                ('ooh', models.IntegerField(default=0, help_text='Out-of-hours timeframe')),
                ('ans_sla', models.CharField(blank=True, max_length=100, null=True)),
                ('abd_sla', models.CharField(blank=True, max_length=100, null=True)),
                ('target_ans_rate', models.FloatField(default=0.8, help_text='Target answer rate (0.0 - 1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('target_abd_rate', models.FloatField(default=0.05, help_text='Target abandon rate (0.0 - 1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SLA Configuration',
                'verbose_name_plural': 'SLA Configurations',
                'db_table': 'sla_config',
                'ordering': ['account'],
            },
        ),
        migrations.CreateModel(
            name='HourlyTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.CharField(db_index=True, max_length=5)),
                ('date', models.DateField(db_index=True)),
                ('account', models.CharField(db_index=True, max_length=100)),
                ('offered', models.IntegerField(default=0)),
                ('abandoned', models.IntegerField(default=0)),
                ('answered', models.IntegerField(default=0)),
                ('sla_rate', models.FloatField(default=0.0)),
                ('abandon_rate', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hourly Trend',
                'verbose_name_plural': 'Hourly Trends',
                'db_table': 'hourly_trends',
                'indexes': [models.Index(fields=['date', 'account'], name='idx_hourly_date_account')],
                'unique_together': {('date', 'hour', 'account')},
            },
        ),
        migrations.CreateModel(
            name='QueueMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue', models.CharField(db_index=True, max_length=200)),
                ('account', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('start_date', models.DateTimeField(db_index=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('hour', models.CharField(db_index=True, help_text='HH:MM format', max_length=5)),
                ('year', models.IntegerField(db_index=True)),
                ('month', models.IntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('week', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(53)])),
                ('day_of_week', models.CharField(blank=True, max_length=20, null=True)),
                ('offered', models.IntegerField(default=0)),
                ('abandoned', models.IntegerField(default=0)),
                ('answered', models.IntegerField(default=0)),
                ('ans_in_sla', models.FloatField(default=0.0)),
                ('abd_in_sla', models.FloatField(default=0.0)),
                ('callback_contacts', models.IntegerField(default=0)),
                ('sla_rate', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('abandon_rate', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('answer_rate', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('avg_handle_time', models.FloatField(default=0.0)),
                ('avg_answer_time', models.FloatField(default=0.0)),
                ('customer_hold_time', models.FloatField(default=0.0)),
                ('target_ans_rate', models.FloatField(default=0.8)),
                ('target_abd_rate', models.FloatField(default=0.05)),
                ('timeframe_bh', models.IntegerField(default=40)),
                ('sla_compliant', models.BooleanField(db_index=True, default=False)),
                ('abd_compliant', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sla_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_metrics', to='api.slaconfig')),
            ],
            options={
                'verbose_name': 'Queue Metric',
                'verbose_name_plural': 'Queue Metrics',
                'db_table': 'queue_metrics',
                'indexes': [models.Index(fields=['account', 'year', 'month'], name='idx_account_period'), models.Index(fields=['start_date', 'account'], name='idx_date_account'), models.Index(fields=['sla_compliant', 'account'], name='idx_compliance_account'), models.Index(fields=['year', 'month', 'week'], name='idx_period')],
            },
        ),
    ]
