# Generated by Django 4.2.9 on 2026-03-03 10:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_queuemetric_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuemetric',
            name='avg_ttc',
            field=models.FloatField(default=0.0, help_text='Avg TTC = Agent interaction time / handled (sec)'),
        ),
        migrations.CreateModel(
            name='RealtimeMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue', models.CharField(db_index=True, max_length=200)),
                ('account', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('language', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('captured_at', models.DateTimeField(db_index=True, help_text='Exact moment this metric was captured')),
                ('hour', models.CharField(help_text='HH:MM format', max_length=5)),
                ('day_of_week', models.CharField(blank=True, max_length=20, null=True)),
                ('offered', models.IntegerField(default=0)),
                ('abandoned', models.IntegerField(default=0)),
                ('answered', models.IntegerField(default=0)),
                ('in_queue', models.IntegerField(default=0, help_text='Contacts currently waiting in queue')),
                ('agents_available', models.IntegerField(default=0)),
                ('agents_busy', models.IntegerField(default=0)),
                ('callback_contacts', models.IntegerField(default=0)),
                ('sla_rate', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('abandon_rate', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('answer_rate', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('avg_handle_time', models.FloatField(default=0.0)),
                ('avg_answer_time', models.FloatField(default=0.0)),
                ('longest_wait_time', models.FloatField(default=0.0, help_text='Longest current wait time in seconds')),
                ('target_ans_rate', models.FloatField(default=0.8)),
                ('target_abd_rate', models.FloatField(default=0.05)),
                ('timeframe_bh', models.IntegerField(default=40)),
                ('sla_compliant', models.BooleanField(db_index=True, default=False)),
                ('source', models.CharField(default='polling', help_text='Data source: polling | webhook | manual', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sla_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='realtime_metrics', to='api.slaconfig')),
            ],
            options={
                'verbose_name': 'Realtime Metric',
                'verbose_name_plural': 'Realtime Metrics',
                'db_table': 'realtime_metrics',
                'ordering': ['-captured_at'],
                'indexes': [models.Index(fields=['captured_at', 'account'], name='idx_rt_captured_account'), models.Index(fields=['account', 'sla_compliant'], name='idx_rt_compliance'), models.Index(fields=['queue', 'captured_at'], name='idx_rt_queue_time')],
            },
        ),
        migrations.CreateModel(
            name='HistoricalMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue', models.CharField(db_index=True, max_length=200)),
                ('account', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('language', models.CharField(blank=True, db_index=True, help_text='Language code, e.g. fr, en, ar, es, de', max_length=10, null=True)),
                ('start_date', models.DateTimeField(db_index=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('hour', models.CharField(help_text='HH:MM format', max_length=5)),
                ('year', models.IntegerField(db_index=True)),
                ('month', models.IntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('week', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(53)])),
                ('day_of_week', models.CharField(blank=True, max_length=20, null=True)),
                ('offered', models.IntegerField(default=0)),
                ('abandoned', models.IntegerField(default=0)),
                ('answered', models.IntegerField(default=0)),
                ('ans_in_sla', models.FloatField(default=0.0)),
                ('abd_in_sla', models.FloatField(default=0.0)),
                ('callback_contacts', models.IntegerField(default=0)),
                ('sla_rate', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('abandon_rate', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('answer_rate', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('avg_handle_time', models.FloatField(default=0.0)),
                ('avg_answer_time', models.FloatField(default=0.0)),
                ('customer_hold_time', models.FloatField(default=0.0)),
                ('avg_ttc', models.FloatField(default=0.0, help_text='Avg TTC = Agent interaction / handled (sec)')),
                ('target_ans_rate', models.FloatField(default=0.8)),
                ('target_abd_rate', models.FloatField(default=0.05)),
                ('timeframe_bh', models.IntegerField(default=40)),
                ('sla_compliant', models.BooleanField(db_index=True, default=False)),
                ('abd_compliant', models.BooleanField(default=False)),
                ('source_file', models.CharField(blank=True, help_text='Source Excel/CSV filename', max_length=255, null=True)),
                ('loaded_at', models.DateTimeField(auto_now_add=True)),
                ('sla_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historical_metrics', to='api.slaconfig')),
            ],
            options={
                'verbose_name': 'Historical Metric',
                'verbose_name_plural': 'Historical Metrics',
                'db_table': 'historical_metrics',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['account', 'year', 'month'], name='idx_hist_account_period'), models.Index(fields=['start_date', 'account'], name='idx_hist_date_account'), models.Index(fields=['year', 'month', 'week'], name='idx_hist_period'), models.Index(fields=['sla_compliant', 'account'], name='idx_hist_compliance')],
            },
        ),
    ]
