# Generated by Django 4.2.9 on 2026-03-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_queuemetric_avg_ttc_realtimemetric_historicalmetric'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsummary',
            name='abd_in_sla',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='accountsummary',
            name='ans_in_sla',
            field=models.FloatField(default=0.0),
        ),
    ]
