# Generated by Django 4.2.9 on 2026-03-03 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_accountsummary_abd_in_sla_accountsummary_ans_in_sla'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsummary',
            name='avg_answer_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='accountsummary',
            name='avg_ttc',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='accountsummary',
            name='timeframe_bh',
            field=models.IntegerField(default=40),
        ),
    ]
