# Generated by Django 4.2.9 on 2026-03-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_accountsummary_avg_answer_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hourlytrend',
            name='abd_in_sla',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='hourlytrend',
            name='ans_in_sla',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='hourlytrend',
            name='answer_rate',
            field=models.FloatField(default=0.0),
        ),
    ]
