# Generated by Django 4.2.9 on 2026-03-06 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_hourlytrend_abd_in_sla_hourlytrend_ans_in_sla_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queuemetric',
            old_name='customer_hold_time',
            new_name='average_hold_time',
        ),
    ]
