# Generated by Django 4.2.9 on 2026-03-06 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_customer_hold_time_queuemetric_average_hold_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalmetric',
            old_name='customer_hold_time',
            new_name='average_hold_time',
        ),
    ]
