# Generated by Django 4.2.9 on 2026-03-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_historicalmetric_customer_hold_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmetric',
            name='abd_out_sla',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalmetric',
            name='ans_out_sla',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='queuemetric',
            name='abd_out_sla',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='queuemetric',
            name='ans_out_sla',
            field=models.IntegerField(default=0),
        ),
    ]
