# Generated by Django 4.2.9 on 2026-03-10 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_historicalmetric_abd_out_sla_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmetric',
            name='handle_time',
            field=models.FloatField(default=0.0, help_text='AHT x answered'),
        ),
        migrations.AddField(
            model_name='historicalmetric',
            name='is_ooh',
            field=models.BooleanField(default=False, help_text='True si weekend ou entre 19h et 7h'),
        ),
        migrations.AddField(
            model_name='historicalmetric',
            name='timeframe_ooh',
            field=models.IntegerField(default=40, help_text='Timeframe hors heures ouvrées (sec)'),
        ),
        migrations.AddField(
            model_name='historicalmetric',
            name='total_answer_time',
            field=models.FloatField(default=0.0, help_text='ASA x answered'),
        ),
        migrations.AddField(
            model_name='historicalmetric',
            name='total_hold_time',
            field=models.FloatField(default=0.0, help_text='Agent interaction time x answered'),
        ),
        migrations.AddField(
            model_name='queuemetric',
            name='handle_time',
            field=models.FloatField(default=0.0, help_text='AHT x answered'),
        ),
        migrations.AddField(
            model_name='queuemetric',
            name='is_ooh',
            field=models.BooleanField(default=False, help_text='True si weekend ou entre 19h et 7h'),
        ),
        migrations.AddField(
            model_name='queuemetric',
            name='timeframe_ooh',
            field=models.IntegerField(default=40, help_text='Timeframe hors heures ouvrées (sec)'),
        ),
        migrations.AddField(
            model_name='queuemetric',
            name='total_answer_time',
            field=models.FloatField(default=0.0, help_text='ASA x answered'),
        ),
        migrations.AddField(
            model_name='queuemetric',
            name='total_hold_time',
            field=models.FloatField(default=0.0, help_text='Agent interaction time x answered'),
        ),
    ]
