# Generated by Django 4.2.9 on 2026-03-28 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014 add desk field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmetric',
            name='abd_in_60',
        ),
        migrations.RemoveField(
            model_name='historicalmetric',
            name='abd_out_60',
        ),
        migrations.AddField(
            model_name='realtimemetric',
            name='desk',
            field=models.CharField(blank=True, db_index=True, help_text='Desk logique (depuis SLA.xlsx Sheet1 colonne Desk)', max_length=200, null=True),
        ),
    ]
