# Generated by Django 4.2.9 on 2026-03-28 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_historicalmetric_abd_in_60_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmetric',
            name='abd_in_60',
            field=models.FloatField(default=0.0, help_text='Abandons dans les 60 premières secondes'),
        ),
        migrations.AddField(
            model_name='historicalmetric',
            name='abd_out_60',
            field=models.FloatField(default=0.0, help_text='Abandons après 60 secondes'),
        ),
    ]
