# Generated by Django 4.2.9 on 2026-04-01 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_historicalmetric_answered_with_hold'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmetric',
            name='total_ttc_time',
            field=models.FloatField(default=0.0, help_text='Agent interaction time x answered (avg_ttc * answered)'),
        ),
        migrations.AlterField(
            model_name='historicalmetric',
            name='total_hold_time',
            field=models.FloatField(default=0.0, help_text='Hold x answered (NaN→0, pas de dilution)'),
        ),
    ]
