# Generated by Django 4.2.9 on 2026-04-01 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_historicalmetric_total_ttc_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmetric',
            name='total_ttc_time',
        ),
    ]
