# Generated by Django 4.2.9 on 2026-04-02 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_historicalmetric_abd_in_60_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsummary',
            name='avg_hold_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='accountsummary',
            name='contacts_put_on_hold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalmetric',
            name='contacts_put_on_hold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='queuemetric',
            name='contacts_put_on_hold',
            field=models.IntegerField(default=0),
        ),
    ]
