# Generated by Django 4.2.9 on 2026-04-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_accountsummary_avg_hold_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountsummary',
            name='avg_hold_time',
        ),
        migrations.RemoveField(
            model_name='accountsummary',
            name='contacts_put_on_hold',
        ),
        migrations.RemoveField(
            model_name='queuemetric',
            name='contacts_put_on_hold',
        ),
        migrations.AlterField(
            model_name='historicalmetric',
            name='contacts_put_on_hold',
            field=models.IntegerField(default=0, help_text='Number of contacts that were put on hold'),
        ),
    ]
