# Generated by Django 4.2.16 on 2026-04-10 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_delete_prediction_slaconfig_other_sla_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slaconfig',
            name='other_sla',
        ),
    ]
