# Generated by Django 4.2.16 on 2026-04-17 21:30

from django.db import migrations, models

DESK_HELP_TEXT = 'Desk logique (depuis SLA.xlsx Sheet1 colonne Desk)'


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_slaconfig_other_sla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmetric',
            name='account',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalmetric',
            name='day_of_week',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalmetric',
            name='desk',
            field=models.CharField(blank=True, db_index=True, default='', help_text=DESK_HELP_TEXT, max_length=200),
        ),
        migrations.AlterField(
            model_name='historicalmetric',
            name='language',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Language code, e.g. fr, en, ar, es, de', max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalmetric',
            name='source_file',
            field=models.CharField(blank=True, default='', help_text='Source Excel/CSV filename', max_length=255),
        ),
        migrations.AlterField(
            model_name='queuemetric',
            name='account',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='queuemetric',
            name='day_of_week',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='queuemetric',
            name='desk',
            field=models.CharField(blank=True, db_index=True, default='', help_text=DESK_HELP_TEXT, max_length=200),
        ),
        migrations.AlterField(
            model_name='queuemetric',
            name='language',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Language code, e.g. fr, en, ar, es, de', max_length=10),
        ),
        migrations.AlterField(
            model_name='realtimemetric',
            name='account',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='realtimemetric',
            name='day_of_week',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='realtimemetric',
            name='desk',
            field=models.CharField(blank=True, db_index=True, default='', help_text=DESK_HELP_TEXT, max_length=200),
        ),
        migrations.AlterField(
            model_name='realtimemetric',
            name='language',
            field=models.CharField(blank=True, db_index=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='slaconfig',
            name='abd_rate_formula',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='slaconfig',
            name='abd_sla',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='slaconfig',
            name='ans_rate_formula',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='slaconfig',
            name='ans_sla',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]