# Generated by Django 4.2.16 on 2026-04-20 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_historicalmetric_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmetric',
            name='account',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmetric',
            name='day_of_week',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmetric',
            name='desk',
            field=models.CharField(blank=True, db_index=True, help_text='Desk logique (depuis SLA.xlsx Sheet1 colonne Desk)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmetric',
            name='language',
            field=models.CharField(blank=True, db_index=True, help_text='Language code, e.g. fr, en, ar, es, de', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmetric',
            name='source_file',
            field=models.CharField(blank=True, help_text='Source Excel/CSV filename', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='queuemetric',
            name='account',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='queuemetric',
            name='day_of_week',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='queuemetric',
            name='desk',
            field=models.CharField(blank=True, db_index=True, help_text='Desk logique (depuis SLA.xlsx Sheet1 colonne Desk)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='queuemetric',
            name='language',
            field=models.CharField(blank=True, db_index=True, help_text='Language code, e.g. fr, en, ar, es, de', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='realtimemetric',
            name='account',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='realtimemetric',
            name='day_of_week',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='realtimemetric',
            name='desk',
            field=models.CharField(blank=True, db_index=True, help_text='Desk logique (depuis SLA.xlsx Sheet1 colonne Desk)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='realtimemetric',
            name='language',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='slaconfig',
            name='abd_rate_formula',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='slaconfig',
            name='abd_sla',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='slaconfig',
            name='ans_rate_formula',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='slaconfig',
            name='ans_sla',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
