from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_historicalmetric_account_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue', models.CharField(max_length=200)),
                ('horizon', models.CharField(max_length=50)),
                ('forecast_date', models.DateField(db_index=True)),
                ('predicted', models.FloatField()),
                ('lower', models.FloatField()),
                ('upper', models.FloatField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={'db_table': 'forecast_results'},
        ),
        migrations.AddIndex(
            model_name='forecastresult',
            index=models.Index(fields=['queue', 'horizon'], name='idx_fc_queue_horizon'),
        ),
        migrations.AddIndex(
            model_name='forecastresult',
            index=models.Index(fields=['forecast_date', 'queue'], name='idx_fc_date_queue'),
        ),
        migrations.RunSQL(
            sql="""
            CREATE TABLE IF NOT EXISTS telephony_data (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                queue varchar(200) NOT NULL,
                start_interval timestamptz NOT NULL,
                end_interval timestamptz,
                abd_in_20s int NOT NULL DEFAULT 0,
                abd_in_30s int NOT NULL DEFAULT 0,
                abd_in_45s int NOT NULL DEFAULT 0,
                abd_in_60s int NOT NULL DEFAULT 0,
                abd_in_90s int NOT NULL DEFAULT 0,
                abd_in_180s int NOT NULL DEFAULT 0,
                abd_in_40s int NOT NULL DEFAULT 0,
                ans_in_20s int NOT NULL DEFAULT 0,
                ans_in_30s int NOT NULL DEFAULT 0,
                ans_in_45s int NOT NULL DEFAULT 0,
                ans_in_60s int NOT NULL DEFAULT 0,
                ans_in_90s int NOT NULL DEFAULT 0,
                ans_in_180s int NOT NULL DEFAULT 0,
                ans_in_40s int NOT NULL DEFAULT 0,
                service_level_60s float NOT NULL DEFAULT 0,
                service_level_120s float NOT NULL DEFAULT 0,
                agent_interaction_time float NOT NULL DEFAULT 0,
                avg_agent_interaction float NOT NULL DEFAULT 0,
                avg_customer_hold_time float NOT NULL DEFAULT 0,
                avg_handle_time float NOT NULL DEFAULT 0,
                avg_queue_abandon_time float NOT NULL DEFAULT 0,
                avg_queue_answer_time float NOT NULL DEFAULT 0,
                api_contacts int NOT NULL DEFAULT 0,
                api_contacts_handled int NOT NULL DEFAULT 0,
                callback_contacts int NOT NULL DEFAULT 0,
                callback_contacts_handled int NOT NULL DEFAULT 0,
                contacts_abandoned int NOT NULL DEFAULT 0,
                contacts_handled_inbound int NOT NULL DEFAULT 0,
                contacts_handled_outbound int NOT NULL DEFAULT 0,
                contacts_put_on_hold int NOT NULL DEFAULT 0,
                contacts_queued int NOT NULL DEFAULT 0,
                loaded_at timestamptz NOT NULL DEFAULT now()
            );
            CREATE INDEX IF NOT EXISTS idx_tel_queue_date ON telephony_data(queue, start_interval);
            """,
            reverse_sql="DROP TABLE IF EXISTS telephony_data;",
        ),
    ]