# Generated by Django 4.2.16 on 2026-05-22 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_historicalmetric_account_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelephonyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue', models.CharField(db_index=True, max_length=200)),
                ('start_interval', models.DateTimeField(db_index=True)),
                ('end_interval', models.DateTimeField(blank=True, null=True)),
                ('abd_in_20s', models.IntegerField(default=0, help_text='Contacts abandoned in 20 seconds')),
                ('abd_in_30s', models.IntegerField(default=0, help_text='Contacts abandoned in 30 seconds')),
                ('abd_in_45s', models.IntegerField(default=0, help_text='Contacts abandoned in 45 seconds')),
                ('abd_in_60s', models.IntegerField(default=0, help_text='Contacts abandoned in 60 seconds')),
                ('abd_in_90s', models.IntegerField(default=0, help_text='Contacts abandoned in 90 seconds')),
                ('abd_in_180s', models.IntegerField(default=0, help_text='Contacts abandoned in 180 seconds')),
                ('ans_in_20s', models.IntegerField(default=0, help_text='Contacts answered in 20 seconds')),
                ('ans_in_30s', models.IntegerField(default=0, help_text='Contacts answered in 30 seconds')),
                ('ans_in_45s', models.IntegerField(default=0, help_text='Contacts answered in 45 seconds')),
                ('ans_in_60s', models.IntegerField(default=0, help_text='Contacts answered in 60 seconds')),
                ('ans_in_90s', models.IntegerField(default=0, help_text='Contacts answered in 90 seconds')),
                ('ans_in_180s', models.IntegerField(default=0, help_text='Contacts answered in 180 seconds')),
                ('service_level_60s', models.FloatField(default=0.0, help_text='Service level 60 seconds')),
                ('service_level_120s', models.FloatField(default=0.0, help_text='Service level 120 seconds')),
                ('agent_interaction_time', models.FloatField(default=0.0)),
                ('avg_agent_interaction', models.FloatField(default=0.0)),
                ('avg_customer_hold_time', models.FloatField(default=0.0)),
                ('avg_handle_time', models.FloatField(default=0.0)),
                ('avg_queue_abandon_time', models.FloatField(default=0.0)),
                ('avg_queue_answer_time', models.FloatField(default=0.0)),
                ('api_contacts', models.IntegerField(default=0)),
                ('api_contacts_handled', models.IntegerField(default=0)),
                ('callback_contacts', models.IntegerField(default=0)),
                ('callback_contacts_handled', models.IntegerField(default=0)),
                ('contacts_abandoned', models.IntegerField(default=0)),
                ('contacts_handled_inbound', models.IntegerField(default=0)),
                ('contacts_handled_outbound', models.IntegerField(default=0)),
                ('contacts_put_on_hold', models.IntegerField(default=0)),
                ('contacts_queued', models.IntegerField(default=0)),
                ('abd_in_40s', models.IntegerField(default=0, help_text='Contacts abandoned in 40 seconds')),
                ('ans_in_40s', models.IntegerField(default=0, help_text='Contacts answered in 40 seconds')),
                ('loaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Telephony Data',
                'verbose_name_plural': 'Telephony Data',
                'db_table': 'telephony_data',
                'ordering': ['-start_interval'],
                'indexes': [models.Index(fields=['queue', 'start_interval'], name='idx_tel_queue_date')],
            },
        ),
        migrations.CreateModel(
            name='ForecastResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue', models.CharField(db_index=True, max_length=200)),
                ('horizon', models.CharField(max_length=10)),
                ('forecast_date', models.DateField(db_index=True)),
                ('predicted', models.FloatField()),
                ('lower', models.FloatField()),
                ('upper', models.FloatField()),
                ('is_weekend', models.BooleanField(default=False)),
                ('is_holiday', models.BooleanField(default=False)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'forecast_results',
                'indexes': [models.Index(fields=['queue', 'horizon'], name='idx_fc_queue_horizon'), models.Index(fields=['forecast_date', 'queue'], name='idx_fc_date_queue')],
                'unique_together': {('queue', 'horizon', 'forecast_date')},
            },
        ),
    ]
