# Generated by Django 4.2.16 on 2026-05-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_forecastresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelephonyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue', models.CharField(db_index=True, max_length=200)),
                ('start_interval', models.DateTimeField(db_index=True)),
                ('end_interval', models.DateTimeField(blank=True, null=True)),
                ('abd_in_20s', models.IntegerField(default=0, help_text='Contacts abandoned in 20 seconds')),
                ('abd_in_30s', models.IntegerField(default=0, help_text='Contacts abandoned in 30 seconds')),
                ('abd_in_45s', models.IntegerField(default=0, help_text='Contacts abandoned in 45 seconds')),
                ('abd_in_60s', models.IntegerField(default=0, help_text='Contacts abandoned in 60 seconds')),
                ('abd_in_90s', models.IntegerField(default=0, help_text='Contacts abandoned in 90 seconds')),
                ('abd_in_180s', models.IntegerField(default=0, help_text='Contacts abandoned in 180 seconds')),
                ('ans_in_20s', models.IntegerField(default=0, help_text='Contacts answered in 20 seconds')),
                ('ans_in_30s', models.IntegerField(default=0, help_text='Contacts answered in 30 seconds')),
                ('ans_in_45s', models.IntegerField(default=0, help_text='Contacts answered in 45 seconds')),
                ('ans_in_60s', models.IntegerField(default=0, help_text='Contacts answered in 60 seconds')),
                ('ans_in_90s', models.IntegerField(default=0, help_text='Contacts answered in 90 seconds')),
                ('ans_in_180s', models.IntegerField(default=0, help_text='Contacts answered in 180 seconds')),
                ('service_level_60s', models.FloatField(default=0.0, help_text='Service level 60 seconds')),
                ('service_level_120s', models.FloatField(default=0.0, help_text='Service level 120 seconds')),
                ('agent_interaction_time', models.FloatField(default=0.0)),
                ('avg_agent_interaction', models.FloatField(default=0.0)),
                ('avg_customer_hold_time', models.FloatField(default=0.0)),
                ('avg_handle_time', models.FloatField(default=0.0)),
                ('avg_queue_abandon_time', models.FloatField(default=0.0)),
                ('avg_queue_answer_time', models.FloatField(default=0.0)),
                ('api_contacts', models.IntegerField(default=0)),
                ('api_contacts_handled', models.IntegerField(default=0)),
                ('callback_contacts', models.IntegerField(default=0)),
                ('callback_contacts_handled', models.IntegerField(default=0)),
                ('contacts_abandoned', models.IntegerField(default=0)),
                ('contacts_handled_inbound', models.IntegerField(default=0)),
                ('contacts_handled_outbound', models.IntegerField(default=0)),
                ('contacts_put_on_hold', models.IntegerField(default=0)),
                ('contacts_queued', models.IntegerField(default=0)),
                ('abd_in_40s', models.IntegerField(default=0, help_text='Contacts abandoned in 40 seconds')),
                ('ans_in_40s', models.IntegerField(default=0, help_text='Contacts answered in 40 seconds')),
                ('loaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Telephony Data',
                'verbose_name_plural': 'Telephony Data',
                'db_table': 'telephony_data',
                'ordering': ['-start_interval'],
            },
        ),
        migrations.AlterModelOptions(
            name='forecastresult',
            options={},
        ),
        migrations.RenameField(
            model_name='forecastresult',
            old_name='created_at',
            new_name='generated_at',
        ),
        migrations.AlterField(
            model_name='forecastresult',
            name='forecast_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='forecastresult',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='forecastresult',
            name='lower',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='forecastresult',
            name='predicted',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='forecastresult',
            name='upper',
            field=models.FloatField(),
        ),
        migrations.AddIndex(
            model_name='forecastresult',
            index=models.Index(fields=['queue', 'horizon'], name='idx_fc_queue_horizon'),
        ),
        migrations.AddIndex(
            model_name='forecastresult',
            index=models.Index(fields=['forecast_date', 'queue'], name='idx_fc_date_queue'),
        ),
        migrations.AlterModelTable(
            name='forecastresult',
            table='forecast_results',
        ),
        migrations.AddIndex(
            model_name='telephonydata',
            index=models.Index(fields=['queue', 'start_interval'], name='idx_tel_queue_date'),
        ),
    ]
