# Generated by Django 4.2.16 on 2026-06-09 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_telephonydata_forecastresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtimemetric',
            name='abd_in_sla',
            field=models.FloatField(default=0.0, help_text='Contacts abandoned within SLA timeframe'),
        ),
        migrations.AddField(
            model_name='realtimemetric',
            name='ans_in_sla',
            field=models.FloatField(default=0.0, help_text='Contacts answered within SLA timeframe'),
        ),
    ]
