# ── BASE ──────────────────────────
FROM node:18-alpine AS base
WORKDIR /app
COPY package*.json ./
RUN npm install

# ── BUILD ─────────────────────────
FROM base AS build
WORKDIR /app
COPY --from=base /app/node_modules ./node_modules   # ← ajouter cette ligne
COPY . .
RUN npm run build

# ── PROD ──────────────────────────
FROM nginx:alpine AS prod
RUN rm -rf /usr/share/nginx/html/*
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]