sonar.projectKey=Rania-Maamer-DXC
sonar.projectName=Rania-Maamer-DXC
sonar.sources=backend
sonar.language=py
sonar.python.version=3.9
sonar.host.url=http://sonarqube:9000

# Coverage
sonar.python.coverage.reportPaths=backend/coverage.xml

# Exclusions de coverage (fichiers non testables)
sonar.coverage.exclusions=\
  backend/manage.py,\
  backend/**/wsgi.py,\
  backend/**/migrations/**,\
  backend/api/management/commands/run_etl.py,\
  backend/api/management/commands/load_today.py,\
  backend/api/management/commands/archive_realtime.py,\
  backend/api/management/commands/archive_to_historical.py,\
  backend/api/management/commands/seed_missing_accounts.py,\
  backend/api/scheduler.py,\
  backend/gunicorn.conf.py,\
  backend/ml_auto_refresh.py