FROM python:3.9

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH="/app"

WORKDIR /app

RUN pip install --upgrade pip

COPY requirements.txt .
RUN pip install -r requirements.txt && \
    python -c "import cmdstanpy; cmdstanpy.install_cmdstan()"

COPY backend/ .
COPY data/ /app/data/

EXPOSE 8000

CMD ["gunicorn", "dxc_backend.wsgi:application", "--bind", "0.0.0.0:8000", "--workers", "3"]